// Generates the 40 player "inks" + 3 colour-vision-deficiency (CVD) palettes.
// Method: candidate colours sampled in OKLCH (mid lightness, firm chroma, for a
// political overlay on a realistic map), then greedy farthest-point selection in OKLab. CVD palettes
// measure distances after a Machado-2009 (severity 1.0) simulation, so colours stay
// separable for protanopes, deuteranopes and tritanopes respectively.
import fs from 'node:fs';
import path from 'node:path';

type Vec3 = [number, number, number];

const linToSrgb = (c: number) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);

function oklabToLinear([L, a, b]: Vec3): Vec3 {
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3,
    m = m_ ** 3,
    s = s_ ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}

function linearToOklab([r, g, b]: Vec3): Vec3 {
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
}

const CVD: Record<string, number[]> = {
  protanopia: [0.152286, 1.052583, -0.204868, 0.114503, 0.786281, 0.099216, -0.003882, -0.048116, 1.051998],
  deuteranopia: [0.367322, 0.860646, -0.227968, 0.280085, 0.672501, 0.047413, -0.01182, 0.04294, 0.968881],
  tritanopia: [1.255528, -0.076749, -0.178779, -0.078411, 0.930809, 0.147602, 0.004733, 0.691367, 0.3039],
};

const mul = (m: number[], [r, g, b]: Vec3): Vec3 => [
  Math.min(1, Math.max(0, m[0]! * r + m[1]! * g + m[2]! * b)),
  Math.min(1, Math.max(0, m[3]! * r + m[4]! * g + m[5]! * b)),
  Math.min(1, Math.max(0, m[6]! * r + m[7]! * g + m[8]! * b)),
];

const dist = (a: Vec3, b: Vec3) => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);

interface Cand {
  lin: Vec3;
  lab: Vec3;
  hex: string;
}

function candidates(): Cand[] {
  const out: Cand[] = [];
  // Political-map inks: mid lightness, firm chroma (no pastels, no neon) so a
  // translucent fill reads clearly over a realistic, daylight terrain.
  for (let L = 0.5; L <= 0.74; L += 0.03) {
    for (let C = 0.11; C <= 0.21; C += 0.02) {
      for (let h = 0; h < 360; h += 3) {
        const a = C * Math.cos((h * Math.PI) / 180),
          b = C * Math.sin((h * Math.PI) / 180);
        const lin = oklabToLinear([L, a, b]);
        if (lin.some((v) => v < -1e-4 || v > 1 + 1e-4)) continue;
        const cl = lin.map((v) => Math.min(1, Math.max(0, v))) as Vec3;
        const hex =
          '#' +
          cl
            .map((v) =>
              Math.round(linToSrgb(v) * 255)
                .toString(16)
                .padStart(2, '0'),
            )
            .join('')
            .toUpperCase();
        out.push({ lin: cl, lab: linearToOklab(cl), hex });
      }
    }
  }
  return out;
}

function pick(cands: Cand[], n: number, space: (c: Cand) => Vec3, normalWeight: number): string[] {
  const proj = cands.map(space);
  const chosen: number[] = [];
  // Start from the most saturated warm red.
  let best = 0,
    bestScore = -1;
  cands.forEach((c, i) => {
    const hue = Math.atan2(c.lab[2], c.lab[1]);
    const chroma = Math.hypot(c.lab[1], c.lab[2]);
    const s = chroma - Math.abs(hue - 0.5) * 0.05;
    if (s > bestScore) {
      bestScore = s;
      best = i;
    }
  });
  chosen.push(best);
  const minD = proj.map(
    (p, i) => dist(p, proj[best]!) + normalWeight * dist(cands[i]!.lab, cands[best]!.lab),
  );
  while (chosen.length < n) {
    let bi = -1,
      bd = -1;
    for (let i = 0; i < cands.length; i++)
      if (minD[i]! > bd) {
        bd = minD[i]!;
        bi = i;
      }
    chosen.push(bi);
    for (let i = 0; i < cands.length; i++) {
      const d = dist(proj[i]!, proj[bi]!) + normalWeight * dist(cands[i]!.lab, cands[bi]!.lab);
      if (d < minD[i]!) minD[i] = d;
    }
  }
  return chosen.map((i) => cands[i]!.hex);
}

const cands = candidates();
const standard = pick(cands, 40, (c) => c.lab, 0);
const cvd: Record<string, string[]> = {};
for (const [name, m] of Object.entries(CVD))
  cvd[name] = pick(cands, 40, (c) => linearToOklab(mul(m, c.lin)), 0.15);

const file = path.resolve(import.meta.dirname, '../../src/render/palette.ts');
fs.writeFileSync(
  file,
  `// GENERATED by scripts/brand/gen-palette.ts — do not edit by hand.
// 40 player inks chosen by farthest-point sampling in OKLab, plus three palettes
// optimised under simulated protanopia / deuteranopia / tritanopia.
export const PLAYER_COLORS: readonly string[] = ${JSON.stringify(standard)};

export const CVD_PALETTES: Readonly<Record<'protanopia' | 'deuteranopia' | 'tritanopia', readonly string[]>> = ${JSON.stringify(cvd, null, 2)};

/** Neutral ink used for tribes (bots) in every palette. */
export const TRIBE_COLOR = '#B9B2A2';
`,
);
console.log('palette written', standard.slice(0, 8));
