// The game's icon vocabulary: one semantic name → one Lucide glyph (ISC licence).
// Used by the <Icon> component (UI) and rasterised into textures for the map.
import {
  Anchor,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircle,
  Ban,
  BarChart3,
  Bomb,
  BookOpen,
  Building2,
  Castle,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleHelp,
  Clock,
  Coins,
  Crosshair,
  Crown,
  Dices,
  Download,
  Eye,
  Factory,
  FastForward,
  Flag,
  FlaskConical,
  Gift,
  Globe,
  Hammer,
  Handshake,
  Info,
  Key,
  Landmark,
  Lock,
  LogOut,
  Map as MapIcon,
  MapPin,
  Maximize2,
  Menu,
  MessageSquare,
  Minimize2,
  Minus,
  Mountain,
  Network,
  Pause,
  Pencil,
  Plane,
  Play,
  Plus,
  Radar,
  Radiation,
  RefreshCw,
  Repeat,
  Rewind,
  Rocket,
  Save,
  ScrollText,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  Ship,
  Skull,
  Sparkles,
  Star,
  Swords,
  Target,
  TrainFront,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Undo2,
  Unlink,
  Upload,
  User,
  Users,
  Volume2,
  Wheat,
  X,
  Zap,
  Droplet,
  Gem,
  Atom,
  Hourglass,
  Sailboat,
  Siren,
  type IconNode,
} from 'lucide';

export const ICONS = {
  // resources & stats
  gold: Coins,
  troops: Swords,
  workers: Hammer,
  population: Users,
  territory: MapIcon,
  income: TrendingUp,
  time: Clock,
  hourglass: Hourglass,
  // buildings
  city: Building2,
  port: Anchor,
  factory: Factory,
  defensePost: Castle,
  silo: Rocket,
  sam: Crosshair,
  radar: Radar,
  airfield: Plane,
  // units & weapons
  warship: Ship,
  transport: Sailboat,
  train: TrainFront,
  nuke: Radiation,
  bomb: Bomb,
  // diplomacy
  alliance: Handshake,
  betrayal: Unlink,
  embargo: Ban,
  gift: Gift,
  war: Swords,
  surrender: Flag,
  diplomacy: Flag,
  renew: Repeat,
  council: Landmark,
  leader: Crown,
  eliminated: Skull,
  traitor: ShieldAlert,
  immune: Shield,
  ceasefire: Handshake,
  // features
  tech: FlaskConical,
  event: Zap,
  general: Star,
  oil: Droplet,
  fertile: Wheat,
  metals: Gem,
  uranium: Atom,
  terrain: Mountain,
  fog: Eye,
  loyalty: Users,
  siren: Siren,
  // ui
  menu: Menu,
  settings: Settings,
  chat: MessageSquare,
  stats: BarChart3,
  log: ScrollText,
  help: CircleHelp,
  info: Info,
  warning: TriangleAlert,
  close: X,
  check: Check,
  plus: Plus,
  minus: Minus,
  back: ArrowLeft,
  next: ArrowRight,
  upgrade: ArrowUpCircle,
  undo: Undo2,
  play: Play,
  pause: Pause,
  forward: FastForward,
  rewind: Rewind,
  lock: Lock,
  key: Key,
  star: Star,
  trophy: Trophy,
  user: User,
  users: Users,
  network: Network,
  globe: Globe,
  dice: Dices,
  edit: Pencil,
  trash: Trash2,
  save: Save,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  target: Target,
  pin: MapPin,
  eye: Eye,
  send: Send,
  book: BookOpen,
  sound: Volume2,
  quit: LogOut,
  expand: Maximize2,
  collapse: Minimize2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  dot: Circle,
  sparkles: Sparkles,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICONS;

const esc = (v: string) => v.replace(/&/g, '&amp;').replace(/"/g, '&quot;');

/** Inner SVG markup of an icon (24×24 viewBox, stroke = currentColor). */
export function iconMarkup(name: IconName): string {
  return (ICONS[name] as IconNode)
    .map(([tag, attrs]) => {
      const a = Object.entries(attrs as Record<string, string | number>)
        .map(([k, v]) => `${k}="${esc(String(v))}"`)
        .join(' ');
      return `<${tag} ${a}/>`;
    })
    .join('');
}

/** A standalone SVG document for an icon (used to rasterise map textures). */
export function iconSvg(name: IconName, color = '#ffffff', strokeWidth = 2, size = 24): string {
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" ` +
    `stroke="${color}" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round">` +
    iconMarkup(name) +
    '</svg>'
  );
}

/** Icon of each building type, in B order. */
export const BUILDING_ICONS: readonly IconName[] = [
  'city',
  'port',
  'factory',
  'defensePost',
  'silo',
  'sam',
  'radar',
  'airfield',
];

/**
 * Tactical map signals (Alt + click): an icon and a short label, shown to the
 * targeted player. The index is the value carried by the 'emoji' command.
 */
export const SIGNALS: readonly { icon: IconName; key: string }[] = [
  { icon: 'war', key: 'attack' },
  { icon: 'immune', key: 'defend' },
  { icon: 'siren', key: 'help' },
  { icon: 'alliance', key: 'alliance' },
  { icon: 'target', key: 'target' },
  { icon: 'eye', key: 'watch' },
  { icon: 'gold', key: 'gold' },
  { icon: 'nuke', key: 'nuke' },
  { icon: 'check', key: 'yes' },
  { icon: 'close', key: 'no' },
  { icon: 'undo', key: 'retreat' },
  { icon: 'warning', key: 'danger' },
  { icon: 'betrayal', key: 'betrayal' },
  { icon: 'transport', key: 'landing' },
  { icon: 'pin', key: 'here' },
  { icon: 'surrender', key: 'peace' },
];
